export let paises = [
  { value: "AD", label: "[AD] Andorra: +376" },
  { value: "AF", label: "[AF] Afghanistan: +93" },
  { value: "AG", label: "[AG] Antigua and Barbuda: +1268" },
  { value: "AI", label: "[AI] Anguilla: +1264" },
  { value: "AL", label: "[AL] Albania: +355" },
  { value: "AM", label: "[AM] Armenia: +374" },
  { value: "AO", label: "[AO] Angola: +244" },
  { value: "AQ", label: "[AQ] Antarctica: +672" },
  { value: "AR", label: "[AR] Argentina: +54" },
  { value: "AS", label: "[AS] American Samoa: +1684" },
  { value: "AT", label: "[AT] Austria: +43" },
  { value: "AU", label: "[AU] Australia: +61" },
  { value: "AW", label: "[AW] Aruba: +297" },
  { value: "AX", label: "[AX] Åland Islands: +358" },
  { value: "AZ", label: "[AZ] Azerbaijan: +994" },
  { value: "BA", label: "[BA] Bosnia and Herzegovina: +387" },
  { value: "BB", label: "[BB] Barbados: +1246" },
  { value: "BD", label: "[BD] Bangladesh: +880" },
  { value: "BE", label: "[BE] Belgium: +32" },
  { value: "BF", label: "[BF] Burkina Faso: +226" },
  { value: "BG", label: "[BG] Bulgaria: +359" },
  { value: "BH", label: "[BH] Bahrain: +973" },
  { value: "BI", label: "[BI] Burundi: +257" },
  { value: "BJ", label: "[BJ] Benin: +229" },
  { value: "BL", label: "[BL] Saint Barthélemy: +590" },
  { value: "BM", label: "[BM] Bermuda: +1441" },
  { value: "BN", label: "[BN] Brunei Darussalam: +673" },
  { value: "BO", label: "[BO] Bolivia (Plurinational State of): +591" },
  { value: "BQ", label: "[BQ] Bonaire, Sint Eustatius and Saba: +5997" },
  { value: "BR", label: "[BR] Brazil: +55" },
  { value: "BT", label: "[BT] Bhutan: +975" },
  { value: "BV", label: "[BV] Bouvet Island: +47" },
  { value: "BW", label: "[BW] Botswana: +267" },
  { value: "BY", label: "[BY] Belarus: +375" },
  { value: "BZ", label: "[BZ] Belize: +501" },
  { value: "CA", label: "[CA] Canada: +1" },
  { value: "CH", label: "[CH] Switzerland: +41" },
  { value: "CI", label: "[CI] Côte d'Ivoire: +225" },
  { value: "CL", label: "[CL] Chile: +56" },
  { value: "CM", label: "[CM] Cameroon: +237" },
  { value: "CN", label: "[CN] China: +86" },
  { value: "CO", label: "[CO] Colombia: +57" },
  { value: "CR", label: "[CR] Costa Rica: +506" },
  { value: "CU", label: "[CU] Cuba: +53" },
  { value: "CV", label: "[CV] Cabo Verde: +238" },
  { value: "CW", label: "[CW] Curaçao: +599" },
  { value: "CX", label: "[CX] Christmas Island: +61" },
  { value: "CY", label: "[CY] Cyprus: +357" },
  { value: "DE", label: "[DE] Germany: +49" },
  { value: "DJ", label: "[DJ] Djibouti: +253" },
  { value: "DK", label: "[DK] Denmark: +45" },
  { value: "DM", label: "[DM] Dominica: +767" },
  { value: "DZ", label: "[DZ] Algeria: +213" },
  { value: "EC", label: "[EC] Ecuador: +593" },
  { value: "EE", label: "[EE] Estonia: +372" },
  { value: "EG", label: "[EG] Egypt: +20" },
  { value: "EH", label: "[EH] Western Sahara: +212" },
  { value: "ER", label: "[ER] Eritrea: +291" },
  { value: "ES", label: "[ES] Spain: +34" },
  { value: "ET", label: "[ET] Ethiopia: +251" },
  { value: "FI", label: "[FI] Finland: +358" },
  { value: "FJ", label: "[FJ] Fiji: +679" },
  { value: "FM", label: "[FM] Micronesia (Federated States of): +691" },
  { value: "FR", label: "[FR] France: +33" },
  { value: "GA", label: "[GA] Gabon: +241" },
  { value: "GD", label: "[GD] Grenada: +1473" },
  { value: "GE", label: "[GE] Georgia: +995" },
  { value: "GF", label: "[GF] French Guiana: +594" },
  { value: "GG", label: "[GG] Guernsey: +44" },
  { value: "GH", label: "[GH] Ghana: +233" },
  { value: "GI", label: "[GI] Gibraltar: +350" },
  { value: "GL", label: "[GL] Greenland: +299" },
  { value: "GN", label: "[GN] Guinea: +224" },
  { value: "GP", label: "[GP] Guadeloupe: +590" },
  { value: "GQ", label: "[GQ] Equatorial Guinea: +240" },
  { value: "GR", label: "[GR] Greece: +30" },
  { value: "GS", label: "[GS] South Georgia and the South Sandwich Islands: +500" },
  { value: "GT", label: "[GT] Guatemala: +502" },
  { value: "GU", label: "[GU] Guam: +1" },
  { value: "GW", label: "[GW] Guinea-Bissau: +245" },
  { value: "GY", label: "[GY] Guyana: +592" },
  { value: "HK", label: "[HK] Hong Kong: +852" },
  { value: "HN", label: "[HN] Honduras: +504" },
  { value: "HR", label: "[HR] Croatia: +385" },
  { value: "HT", label: "[HT] Haiti: +509" },
  { value: "HU", label: "[HU] Hungary: +36" },
  { value: "ID", label: "[ID] Indonesia: +62" },
  { value: "IE", label: "[IE] Ireland: +353" },
  { value: "IL", label: "[IL] Israel: +972" },
  { value: "IM", label: "[IM] Isle of Man: +44" },
  { value: "IN", label: "[IN] India: +91" },
  { value: "IQ", label: "[IQ] Iraq: +964" },
  { value: "IR", label: "[IR] Iran (Islamic Republic of): +98" },
  { value: "IS", label: "[IS] Iceland: +354" },
  { value: "IT", label: "[IT] Italy: +39" },
  { value: "JE", label: "[JE] Jersey: +44" },
  { value: "JM", label: "[JM] Jamaica: +876" },
  { value: "JO", label: "[JO] Jordan: +962" },
  { value: "JP", label: "[JP] Japan: +81" },
  { value: "KE", label: "[KE] Kenya: +254" },
  { value: "KG", label: "[KG] Kyrgyzstan: +996" },
  { value: "KH", label: "[KH] Cambodia: +855" },
  { value: "KP", label: "[KP] North Korea: +850" },
  { value: "KR", label: "[KR] South Korea: +82" },
  { value: "KI", label: "[KI] Kiribati: +686" },
  { value: "KN", label: "[KN] Saint Kitts and Nevis: +1869" },
  { value: "KW", label: "[KW] Kuwait: +965" },
  { value: "KZ", label: "[KZ] Kazakhstan: +7" },
  { value: "LB", label: "[LB] Lebanon: +961" },
  { value: "LC", label: "[LC] Saint Lucia: +1758" },
  { value: "LI", label: "[LI] Liechtenstein: +423" },
  { value: "LK", label: "[LK] Sri Lanka: +94" },
  { value: "LR", label: "[LR] Liberia: +231" },
  { value: "LS", label: "[LS] Lesotho: +266" },
  { value: "LT", label: "[LT] Lithuania: +370" },
  { value: "LU", label: "[LU] Luxembourg: +352" },
  { value: "LV", label: "[LV] Latvia: +371" },
  { value: "LY", label: "[LY] Libya: +218" },
  { value: "MA", label: "[MA] Morocco: +212" },
  { value: "MC", label: "[MC] Monaco: +377" },
  { value: "ME", label: "[ME] Montenegro: +382" },
  { value: "MF", label: "[MF] Saint Martin (French part): +590" },
  { value: "MG", label: "[MG] Madagascar: +261" },
  { value: "ML", label: "[ML] Mali: +223" },
  { value: "MM", label: "[MM] Myanmar: +95" },
  { value: "MN", label: "[MN] Mongolia: +976" },
  { value: "MO", label: "[MO] Macao: +853" },
  { value: "MQ", label: "[MQ] Martinique: +596" },
  { value: "MR", label: "[MR] Mauritania: +222" },
  { value: "MS", label: "[MS] Montserrat: +1664" },
  { value: "MT", label: "[MT] Malta: +356" },
  { value: "MU", label: "[MU] Mauritius: +230" },
  { value: "MV", label: "[MV] Maldives: +960" },
  { value: "MW", label: "[MW] Malawi: +265" },
  { value: "MX", label: "[MX] Mexico: +52" },
  { value: "MY", label: "[MY] Malaysia: +60" },
  { value: "MZ", label: "[MZ] Mozambique: +258" },
  { value: "NA", label: "[NA] Namibia: +264" },
  { value: "NC", label: "[NC] New Caledonia: +687" },
  { value: "NF", label: "[NF] Norfolk Island: +672" },
  { value: "NG", label: "[NG] Nigeria: +234" },
  { value: "NI", label: "[NI] Nicaragua: +505" },
  { value: "NO", label: "[NO] Norway: +47" },
  { value: "NP", label: "[NP] Nepal: +977" },
  { value: "NR", label: "[NR] Nauru: +674" },
  { value: "NU", label: "[NU] Niue: +683" },
  { value: "NZ", label: "[NZ] New Zealand: +64" },
  { value: "OM", label: "[OM] Oman: +968" },
  { value: "PA", label: "[PA] Panama: +507" },
  { value: "PE", label: "[PE] Peru: +51" },
  { value: "PF", label: "[PF] French Polynesia: +689" },
  { value: "PG", label: "[PG] Papua New Guinea: +675" },
  { value: "PK", label: "[PK] Pakistan: +92" },
  { value: "PL", label: "[PL] Poland: +48" },
  { value: "PM", label: "[PM] Saint Pierre and Miquelon: +508" },
  { value: "PN", label: "[PN] Pitcairn: +64" },
  { value: "PR", label: "[PR] Puerto Rico: +1" },
  { value: "PS", label: "[PS] Palestine, State of: +970" },
  { value: "PT", label: "[PT] Portugal: +351" },
  { value: "PW", label: "[PW] Palau: +680" },
  { value: "PY", label: "[PY] Paraguay: +595" },
  { value: "QA", label: "[QA] Qatar: +974" },
  { value: "RE", label: "[RE] Réunion: +262" },
  { value: "RO", label: "[RO] Romania: +40" },
  { value: "RS", label: "[RS] Serbia: +381" },
  { value: "RU", label: "[RU] Russia: +7" },
  { value: "RW", label: "[RW] Rwanda: +250" },
  { value: "SA", label: "[SA] Saudi Arabia: +966" },
  { value: "SB", label: "[SB] Solomon Islands: +677" },
  { value: "SC", label: "[SC] Seychelles: +248" },
  { value: "SE", label: "[SE] Sweden: +46" },
  { value: "SG", label: "[SG] Singapore: +65" },
  { value: "SH", label: "[SH] Saint Helena, Ascension and Tristan da Cunha: +290" },
  { value: "SI", label: "[SI] Slovenia: +386" },
  { value: "SJ", label: "[SJ] Svalbard and Jan Mayen: +4779" },
  { value: "SK", label: "[SK] Slovakia: +421" },
  { value: "SL", label: "[SL] Sierra Leone: +232" },
  { value: "SM", label: "[SM] San Marino: +378" },
  { value: "SN", label: "[SN] Senegal: +221" },
  { value: "SO", label: "[SO] Somalia: +252" },
  { value: "SR", label: "[SR] Suriname: +597" },
  { value: "SS", label: "[SS] South Sudan: +211" },
  { value: "ST", label: "[ST] Sao Tome and Principe: +239" },
  { value: "SV", label: "[SV] El Salvador: +503" },
  { value: "SX", label: "[SX] Sint Maarten (Dutch part): +1721" },
  { value: "SY", label: "[SY] Syrian Arab Republic: +963" },
  { value: "TD", label: "[TD] Chad: +235" },
  { value: "TG", label: "[TG] Togo: +228" },
  { value: "TH", label: "[TH] Thailand: +66" },
  { value: "TJ", label: "[TJ] Tajikistan: +992" },
  { value: "TK", label: "[TK] Tokelau: +690" },
  { value: "TL", label: "[TL] Timor-Leste: +670" },
  { value: "TM", label: "[TM] Turkmenistan: +993" },
  { value: "TN", label: "[TN] Tunisia: +216" },
  { value: "TO", label: "[TO] Tonga: +676" },
  { value: "TR", label: "[TR] Turkey: +90" },
  { value: "TT", label: "[TT] Trinidad and Tobago: +868" },
  { value: "TV", label: "[TV] Tuvalu: +688" },
  { value: "TZ", label: "[TZ] United Republic of Tanzania: +255" },
  { value: "UA", label: "[UA] Ukraine: +380" },
  { value: "UG", label: "[UG] Uganda: +256" },
  { value: "US", label: "[US] United States of America: +1" },
  { value: "UY", label: "[UY] Uruguay: +598" },
  { value: "UZ", label: "[UZ] Uzbekistan: +998" },
  { value: "VC", label: "[VC] Saint Vincent and the Grenadines: +1784" },
  { value: "VE", label: "[VE] Venezuela (Bolivarian Republic of): +58" },
  { value: "VG", label: "[VG] Virgin Islands (British): +1284" },
  { value: "VI", label: "[VI] Virgin Islands (U.S.): +1340" },
  { value: "VN", label: "[VN] Vietnam: +84" },
  { value: "VU", label: "[VU] Vanuatu: +678" },
  { value: "WF", label: "[WF] Wallis and Futuna: +681" },
  { value: "WS", label: "[WS] Samoa: +685" },
  { value: "YE", label: "[YE] Yemen: +967" },
  { value: "YT", label: "[YT] Mayotte: +262" },
  { value: "ZA", label: "[ZA] South Africa: +27" },
  { value: "ZM", label: "[ZM] Zambia: +260" },
  { value: "ZW", label: "[ZW] Zimbabwe: +263" },
  { value: "SZ", label: "[SZ] Eswatini: +268" },
  { value: "MK", label: "[MK] North Macedonia: +389" },
  { value: "PH", label: "[PH] Philippines: +63" },
  { value: "NL", label: "[NL] Netherlands: +31" },
  { value: "AE", label: "[AE] United Arab Emirates: +971" },
  { value: "MD", label: "[MD] Republic of Moldova: +373" },
  { value: "GM", label: "[GM] Gambia: +220" },
  { value: "DO", label: "[DO] Dominican Republic: +1" },
  { value: "SD", label: "[SD] Sudan: +249" },
  { value: "LA", label: "[LA] Lao People's Democratic Republic: +856" },
  { value: "TW", label: "[TW] Taiwan, Province of China: +886" },
  { value: "CG", label: "[CG] Republic of the Congo: +242" },
  { value: "CZ", label: "[CZ] Czechia: +420" },
  { value: "GB", label: "[GB] United Kingdom: +44" },
  { value: "NE", label: "[NE] Niger: +227" },
  { value: "CD", label: "[CD] Democratic Republic of the Congo: +243" },
  { value: "BS", label: "[BS] Commonwealth of The Bahamas: +1 242" },
  { value: "CC", label: "[CC] Cocos (Keeling) Islands: +61 891" },
  { value: "CF", label: "[CF] Central African Republic: +236" },
  { value: "CK", label: "[CK] Cook Islands: +682" },
  { value: "FK", label: "[FK] Falkland Islands: +500" },
  { value: "FO", label: "[FO] Faroe Islands: +298" },
  { value: "HM", label: "[HM] Territory of Heard Island and McDonald Islands: +672" },
  { value: "IO", label: "[IO] British Indian Ocean Territory: +246" },
  { value: "KM", label: "[KM] Comoros: +269" },
  { value: "KY", label: "[KY] Cayman Islands: +1 345" },
  { value: "MH", label: "[MH] Republic of the Marshall Islands: +692" },
  { value: "MP", label: "[MP] Commonwealth of the Northern Mariana Islands: +1 670" },
  { value: "TC", label: "[TC] Turks and Caicos Islands: +1 649" },
  { value: "TF", label: "[TF] French Southern and Antarctic Lands: +672" },
  { value: "UM", label: "[UM] United States Minor Outlying Islands: +246" },
  { value: "VA", label: "[VA] Holy See: +3" }
];